/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_testdemo_jnitest_JniTestNative */

#ifndef _Included_com_testdemo_jnitest_JniTestNative
#define _Included_com_testdemo_jnitest_JniTestNative
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_testdemo_jnitest_JniTestNative
 * Method:    getString
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_testdemo_jnitest_JniTestNative_getString
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
